# Generated by Django 5.1.6 on 2025-02-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="family_name",
            field=models.CharField(default="user", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="given_name",
            field=models.CharField(default="admin", max_length=254),
        ),
    ]
