# Generated by Django 5.1.6 on 2025-03-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_family_name_alter_user_given_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profiles/default.png", upload_to="profiles/"
            ),
        ),
    ]
