# Generated by Django 5.1.6 on 2025-03-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profiles/default-avatar.png", upload_to="profiles/"
            ),
        ),
    ]
