# Generated by Django 5.1.6 on 2025-03-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_boardgame_remove_user_profile_picture_borrowedgame"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowedgame",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
