# Generated by Django 5.1.6 on 2025-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_borrowedgame_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedgame",
            name="borrowed_on",
            field=models.DateTimeField(),
        ),
    ]
