# Generated by Django 5.1.6 on 2025-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_borrowedgame_borrowed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profiles/default-avatar.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
