# Generated by Django 5.1.6 on 2025-03-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="images/default-avatar.jpg", upload_to="profiles/"
            ),
        ),
    ]
