# Generated by Django 5.1.6 on 2025-03-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardgame",
            options={"ordering": ["title"], "verbose_name": "Board Game"},
        ),
        migrations.AddField(
            model_name="boardgame",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="board_games/"),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.CreateModel(
            name="GameLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_on", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateTimeField(auto_now=True)),
                ("returned", models.BooleanField(default=False)),
                ("returned_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrowed", "Borrowed"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        default="borrowed",
                        max_length=10,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_instances",
                        to="users.boardgame",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lent_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Loan",
                "verbose_name_plural": "Game Loans",
                "ordering": ["-borrowed_on"],
            },
        ),
        migrations.DeleteModel(
            name="BorrowedGame",
        ),
        migrations.AddIndex(
            model_name="gameloan",
            index=models.Index(
                fields=["user", "returned"], name="users_gamel_user_id_848f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gameloan",
            index=models.Index(
                fields=["due_date"], name="users_gamel_due_dat_3be31b_idx"
            ),
        ),
    ]
