# Generated by Django 5.1.6 on 2025-03-25 22:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_boardgame_options_boardgame_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when this copy was added to the collection",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this copy is available for borrowing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Copy",
                "verbose_name_plural": "Game Copies",
                "ordering": ["game__title", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="boardgame",
            options={
                "ordering": ["title"],
                "verbose_name": "Board Game",
                "verbose_name_plural": "Board Games",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="gameloan",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gameloan",
            name="lender",
        ),
        migrations.AddField(
            model_name="boardgame",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Game complexity from 1 (simple) to 5 (complex)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="max_players",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="min_players",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="playing_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Average playing time in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="gameloan",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gameloan",
            name="borrowed_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gameloan",
            name="due_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="family_name",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="given_name",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user can access the admin site.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
            ),
        ),
        migrations.AddField(
            model_name="boardgame",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="users.category"
            ),
        ),
        migrations.AddIndex(
            model_name="boardgame",
            index=models.Index(fields=["title"], name="users_board_title_b36735_idx"),
        ),
        migrations.AddField(
            model_name="gamecopy",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="users.boardgame",
            ),
        ),
        migrations.AddField(
            model_name="gameloan",
            name="game_copy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="users.gamecopy",
            ),
        ),
        migrations.AddIndex(
            model_name="gameloan",
            index=models.Index(fields=["status"], name="users_gamel_status_20c2e8_idx"),
        ),
        migrations.AddField(
            model_name="review",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.boardgame",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "game")},
        ),
    ]
