# Generated by Django 5.1.6 on 2025-03-26 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_create_default_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can view this private collection",
                        related_name="accessible_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        blank=True, related_name="collections", to="users.boardgame"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="users_colle_title_492b4e_idx")
                ],
            },
        ),
    ]
