# Generated by Django 5.1.6 on 2025-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamecopy",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("shannon", "Shannon Library"),
                    ("clark", "Clark Library"),
                    ("clemons", "Clemons Library"),
                ],
                default="shannon",
                help_text="Location where this game copy can be picked up",
                max_length=20,
            ),
        ),
    ]
