# Generated by Django 5.1.6 on 2025-05-07 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_borrowrequest_collectionaccessrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="playing_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Average playing time in minutes",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
